### ISSUE TITLE
Terminal color support not cached

### ISSUE THREAD

**Issue by andrewo37** [r3bl-org/r3bl_ansi_color#6]
`detect_color_support.rs` should store color support after first run of `supports_color()`

**Comment by nazmulidris** [comment]
@andrewo37 Great point! We have an example of memoizing a computation here
https://github.com/r3bl-org/r3bl_ansi_color/blob/main/src/color_support_override.rs#L29
We can apply a similar pattern to get this done.

**Comment by nazmulidris** [comment]
@andrewo37 one way to memoize the result of the computation (checking to see what the color capabilities of the given stream are) is to use `once_cell` (which is replacing lazy_static): https://docs.rs/once_cell/latest/once_cell/

We might have to pay attention memoizing both streams, since there are two variants of it.
https://github.com/r3bl-org/r3bl_ansi_color/blob/main/src/detect_color_support.rs#L33
